# Generated by Django 4.2.6 on 2023-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(null=True, to='filmes.filme'),
        ),
    ]
