# Generated by Django 4.2.6 on 2023-11-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_alter_usuario_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, null=True, to='filmes.filme'),
        ),
    ]
